name: OWASP ZAP DAST Workflow

on:
  push:
    branches:
      - fatima
  pull_request:
permissions:
  issues: write
  contents: write

jobs:
  dast:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull Juice Shop Docker Image and Run It
      - name: Start Juice Shop Application
        run: |
          docker run --rm -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
          sleep 15 # Wait for the app to be ready
          
      - name: Set Write Permissions for the ZAP Volume
        run: chmod -R 777 $(pwd)

      # Step 2: Pull OWASP ZAP Docker Image and Run the Scan
      - name: Run OWASP ZAP Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw --network="host" \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://127.0.0.1:3000 \
            -J zap-report.json -w zap-report.md -r zap-report.html

      # Step 3: Upload the ZAP Report as an Artifact
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            zap-report.json
            zap-report.md
            zap-report.html
