name: OWASP ZAP DAST Workflow

on:
  push:
    branches:
      - fatima
  pull_request:

jobs:
  dast:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Start the App
      - name: Start App
        run: npm start &
      
      
      # Step 4: Perform ZAP Scan
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # Replace with localhost or ngrok URL
          target: 'http://localhost:3000' 
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload ZAP Report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: owasp-zap-report.html
