name: Snyk SCA Workflow

on:
  push:
    branches:
      - fatima
  pull_request:

jobs:
  snyk-sca:
    name: Snyk Software Composition Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install # Ensure dependencies are installed for the test to work

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk JSON Results
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk-results.json
