name: Snyk SCA Workflow

on:
  push:
    branches:
      - fatima
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Snyk to Check for Vulnerabilities
        uses: snyk/actions@v1.11.1
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.GITHUB_TOKEN }}
