name: CI/CD Pipeline

on:
  push:
    branches:
      - fatima
  pull_request:
    branches:
      - fatima

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 6: SonarCloud analysis
    - name: SonarCloud Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=fatimamlk_Devsecops \
          -Dsonar.organization=fatimamlk \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
