name: CI/CD Pipeline

on:
  push:
    branches:
      - fatima
  pull_request:
    branches:
      - fatima

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 5: Run tests
    - name: Run Tests
      run: mvn test

    # Step 6: SonarCloud analysis
    - name: SonarCloud Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=fatimamlk_Devsecops \
          -Dsonar.organization=fatimamlk \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
